### PR TITLE
Added ValueChangeMode for faster value-change tracking in wysiwyg-e.

### PR DESCRIPTION
**Pull request by jkoenig134**
I need this for saving while user is typing.

### CODE REVIEW

**Comment by chufgard** [comment]
Would be great if this feature could be added asap. I'd like to use it too and even thought its absence was a bug. :)

**Comment by jkoenig134** [comment]
@chufgard my Version is available via jitpack.io, you can use it!

**Comment by chufgard** [comment]
> @chufgard my Version is available via jitpack.io, you can use it!

How do I find it there? And would it be possible for you to merge / rebase with the latest changes, such that a merging with master here is possible again?

**Comment by pleku** [comment]
Thanks for the contribution, adopted in #9

**Comment by jkoenig134** [comment]
@pleku thanks!

**Pull request closed without merging**
